export const FIXED_NFE_EMITENTE_NAME = 'M. G. A. IMPORTACAO, INDUSTRIA E COMERCIO DE ALIMENTOS LTDA';
export const FIXED_NFE_EMITENTE_CNPJ = '60.356.037/0001-89';

export const FIXED_NFE_TRANSPORTADORA_NAME = 'ID Transportes';
export const FIXED_NFE_TRANSPORTADORA_CNPJ = '44.038.678/0001-39';
